#!/bin/bash

if [[ -z "$1" || -z "$2" ]]; then
  echo "usage: $0 CLUSTER APISERVER"
  exit 1
fi

CLUSTER="$1"
APISERVER="$2"

kubectl config set-cluster "$CLUSTER" \
  --server="$APISERVER" --certificate-authority="/dev/null" --embed-certs
kubectl config set-credentials "$USER" \
  --exec-api-version="client.authentication.k8s.io/v1alpha1" \
  --exec-command="aws" --exec-arg="eks" --exec-arg="get-token" \
  --exec-arg="--cluster-name" --exec-arg="$CLUSTER"
kubectl config set-context "$CLUSTER" --cluster="$CLUSTER" --user="$USER"
kubectl config use-context "$CLUSTER"
